version: '3.8'
services:
  postgres:
    image: 'postgres:14-alpine'
    volumes:
      - data-volume:/var/lib/postgresql/data
    ports:
      - '5454:5432'
    environment:
      TZ: "Europe/Oslo"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

volumes:
  data-volume:
