server:
  host: ${SERVER_HOST:-127.0.0.1}
  port: ${SERVER_PORT:-8080}

database:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  jdbcUrl: ${DATABASE_JDBC_URL}

dummyJsonClient:
  baseUrl: ${DUMMY_JSON_BASE_URL}